CC = g++

TARGET = sorts

FLAGS = -std=c++2b -g

$(TARGET): JacobKCST211Lab8Sorts.cpp Array.h BST.h Exception.h Hash.h List.h Queue.h LNode.h TNode.h
	$(CC) $(FLAGS) -o $(TARGET) JacobKCST211Lab8Sorts.cpp Array.h BST.h Exception.h Hash.h List.h Queue.h LNode.h TNode.h

clean:
	$(RM) $(TARGET)
