CC = g++

TARGET = sorts

FLAGS = -std=c++2b -O3

$(TARGET): JacobKCST211Lab7Sorts.cpp Array.h Exception.h Sorts.h
	$(CC) $(FLAGS) -o $(TARGET) JacobKCST211Lab7Sorts.cpp Array.h Exception.h Sorts.h

clean:
	$(RM) $(TARGET)
